language: node_js
node_js:
  - "0.10"
  - "10"

branches:
  only:
    - master

before_install:
  - npm i -g npm
  # Workaround for a permissions issue with Travis virtual machine images
script:
  - npm test